import { LocalStore } from "../storage/localStore.js";
import ProviderRunner from "./providerRunner.js";

const KEY = "pluginSources";

function normalizeSources(input) {
  if (!Array.isArray(input)) {
    return [];
  }
  return input
    .map((source) => ({
      id: source.id || `plugin_${Math.random().toString(36).slice(2, 10)}`,
      name: String(source.name || "Custom Source").trim(),
      urlTemplate: String(source.urlTemplate || "").trim(),
      enabled: source.enabled !== false
    }))
    .filter((source) => Boolean(source.urlTemplate));
}

function applyTemplate(template, vars) {
  let output = template;
  Object.entries(vars).forEach(([key, value]) => {
    const token = `{${key}}`;
    output = output.split(token).join(String(value ?? ""));
  });
  return output;
}

export const PluginRuntime = {
  listSources() {
    return normalizeSources(LocalStore.get(KEY, []));
  },

  saveSources(sources) {
    LocalStore.set(KEY, normalizeSources(sources));
  },

  addSource(source) {
    const current = this.listSources();
    current.push(source);
    this.saveSources(current);
  },

  removeSource(sourceId) {
    const next = this.listSources().filter((source) => source.id !== sourceId);
    this.saveSources(next);
  },

  setSourceEnabled(sourceId, enabled) {
    const next = this.listSources().map((source) => {
      if (source.id !== sourceId) {
        return source;
      }
      return { ...source, enabled: Boolean(enabled) };
    });
    this.saveSources(next);
  },

  async execute({ tmdbId, mediaType, season = null, episode = null } = {}) {
    const vars = {
      tmdbId: tmdbId || "",
      mediaType: mediaType || "",
      season: season ?? "",
      episode: episode ?? ""
    };
    const results = [];
    for (const source of this.listSources().filter((s) => s.enabled)) {
      const url = applyTemplate(source.urlTemplate, vars).trim();
      if (!url) continue;

      // If source looks like a JS provider (ends with .js or contains /src/providers/), try ProviderRunner
      const isProviderJs = /\.js($|\?|#)/i.test(url) || /\/src\/providers\//i.test(url);
      if (isProviderJs) {
        try {
          const streams = await ProviderRunner.runProviderScript(url, {
            tmdbId: vars.tmdbId,
            mediaType: vars.mediaType,
            season: vars.season,
            episode: vars.episode
          });
          const mapped = (streams || []).map((s) => ({
            name: s.name || s.meta?.title || `${source.name} Stream`,
            title: s.title || s.meta?.title || null,
            url: s.url || s.file || s.stream || null,
            description: s.description || (s.meta && s.meta.title) || null,
            quality: s.quality || null,
            subtitles: Array.isArray(s.subtitles) ? s.subtitles : []
          })).filter((s) => s.url);

          results.push({ sourceId: source.id, sourceName: source.name, streams: mapped });
          continue;
        } catch (e) {
          console.warn('Provider execution failed for', url, e);
        }
      }

      // Fallback: treat as a template URL
      results.push({
        sourceId: source.id,
        sourceName: source.name,
        streams: [
          {
            name: `${source.name} Source`,
            title: `${source.name} Stream`,
            url,
            description: `Generated by template: ${source.urlTemplate}`
          }
        ]
      });
    }

    return results;
  }
};
